### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-2-evaluacion-intermedia-includepatriciamartinez#1]
Hola @includepatriciamartinez quieres acabar el ejercicio antes de que te lo corrija?

**Comment by includepatriciamartinez** [comment]
Hola @migueldelmazo yo quiero hacerlo si, de cuánto tiempo dispongo? Me pongo ahora con ello.

**Comment by migueldelmazo** [comment]
Hellooouu del tiempo que quieras @includepatriciamartinez el objetivo es aprender!!!

**Comment by includepatriciamartinez** [comment]
pues si me aguantas a que esta tarde repase eventos y me aventuro ente hoy y mañana a repetirla para practicar con un ejercicio completo, muy agradecida. Mi objetivo es aprender así que lo de suspender me frustra más que asusta. Gracias @migueldelmazo , te aviso cuando la tenga ;)

**Comment by includepatriciamartinez** [comment]
Hola Miguel, ya he rehecho mi evaluación intermedia del módulo 2. Queda pendiente de terminar el contador que no tengo claro cómo debo hacerlo. Puedes pasarla por el boot. Gracias.
